name: Rust

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.container.os }}
    strategy:
      matrix:
        rust:
          - toolchain: nightly
            features: "--no-default-features --features=unstable"
          - toolchain: stable
            features: "--no-default-features --features=undefined_behavior"
        container:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust.toolchain }}
        override: true
    - uses: actions/cache@v2
      with:
        path: |
          Cargo.lock
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.rust.toolchain }}-cargo-${{ hashFiles('**/Cargo.toml') }}
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo clean -p dst && cargo test --verbose ${{ matrix.rust.features }}
